//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dip_SWD_EndSem1Challenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ClientID { get; set; }
        public string TourName { get; set; }
        public string EventMonth { get; set; }
        public int EventDay { get; set; }
        public int EventYear { get; set; }
        public int Payment { get; set; }
        public System.DateTime DateBooked { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
