CREATE TABLE [dbo].[Bookings]
(
	[ClientID] INT NOT NULL,
	[TourName] NVARCHAR(100) NOT NULL,
	[EventMonth] NVARCHAR(5) NOT NULL,
	[EventDay] INT NOT NULL,
	[EventYear] INT NOT NULL,
	[Payment] INT NOT NULL,
	[DateBooked] DATE NOT NULL,
	CONSTRAINT PK_BookingID PRIMARY KEY (ClientID, TourName, DateBooked),
	CONSTRAINT FK_CLIENTS FOREIGN KEY (ClientID) REFERENCES Clients (ClientID),
	CONSTRAINT FK_TOURS FOREIGN KEY (TourName) REFERENCES Tours (TourName),
	--CONSTRAINT FK_TOUREVENTS_EVENTMONTH FOREIGN KEY (EventMonth) REFERENCES TourEvents (EventMonth),
	--CONSTRAINT FK_TOUREVENTS_EVENTDAY FOREIGN KEY (EventDay) REFERENCES TourEvents (EventDay),
	--CONSTRAINT FK_TOUREVENTS_EVENTYEAR FOREIGN KEY (EventYear) REFERENCES TourEvents (EventYear)

)
